version: 0.2

phases:
  install:

    runtime-versions:
      nodejs: 12
    commands:
      - node -v

  pre_build:
    commands:
      - npm install
      - echo pre build
  
  build:
    commands:
      - npm run build
  
  post_build:
    commands:
      - aws s3 sync ./build s3://$BUCKET_S3_HOST_NAME
      - aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"